// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugpdapwstzkwhqsixnae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncGRhcHdzdHprd2hxc2l4bmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Mjc0NDYsImV4cCI6MjA3NzQwMzQ0Nn0.pq7B7fArujrhTfPZqlc2HW7BjmZkxydd2QpN1yl3MTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});